version: '3.8'

services:
  rabbit:
    image: rabbitmq:3-management-alpine
    ports:
      - ${RABBITMQ_PORT}:5672
      - ${RABBITMQ_UI_PORT}:15672
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 1s
      timeout: 1s
      retries: 30